# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Arathis'壁垒
email: ssdfa7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  咸鱼湾非洲提督，垫底鸟厨，暂时失业的全栈工程师Arathi的博客
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.arathi.pw" # the base hostname & protocol for your site
twitter_username: __Arathi_R
github_username:  Arathi

# Build settings
markdown: kramdown
